name: Deploy to Remote via rsync

on:
  push:
    branches: [ main ]   # change if your default branch is different
  workflow_dispatch:      # allow manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Load your private key from GitHub Secrets
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # If your key has a passphrase, also set SSH_PASSPHRASE secret and uncomment:
          # ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      # Trust the remote host (avoids interactive prompt)
      - name: Add server to known_hosts
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts

      # Ensure target directory exists
      - name: Create target directory (if needed)
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          ssh "$REMOTE_USER@$REMOTE_HOST" "mkdir -p '$REMOTE_PATH'"

      # Sync files, respecting .gitignore
      - name: Rsync to remote
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          rsync -az --delete \
            --filter=':- .gitignore' \
            --exclude='.git/' \
            ./ "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
